openapi: 3.0.1
info:
  title: HealthCheck v1
  description: This app polls periodically the status of the services that belong
    to a user.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
tags:
  - name: service
    description: Services management
    externalDocs:
      description: More information
      url: https://github.com/rwngallego/healthcheck/blob/master/docs/design.md
  - name: user
    description: User management
    externalDocs:
      description: More information
      url: https://github.com/rwngallego/healthcheck/blob/master/docs/design.md
  - name: auth
    description: Authentication management
    externalDocs:
      description: More information
      url: https://github.com/rwngallego/healthcheck/blob/master/docs/design.md
paths:
  /services:
    get:
      tags:
        - service
      summary: Get all services
      description: Get the list of services
      operationId: servicesByUser
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Service'
        400:
          description: Invalid ID
          content: {}
        404:
          description: Not found
          content: {}
      security:
        - bearer: []
    post:
      tags:
        - service
      summary: Create a new service
      description: Create a new service
      operationId: createService
      requestBody:
        description: The service information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
        required: true
      responses:
        200:
          description: successful operation
          content: {}
        400:
          description: Validation error
          content: {}
      security:
        - bearer: []
  /services/{serviceId}:
    put:
      tags:
        - service
      summary: Update service
      description: Update the service information
      operationId: updateService
      parameters:
        - name: serviceId
          in: path
          description: Service ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: The service information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
        required: true
      responses:
        200:
          description: successful operation
          content: {}
        400:
          description: Validation error
          content: {}
      security:
        - bearer: []
    delete:
      tags:
        - service
      summary: Delete service
      description: Delete the service
      operationId: deleteService
      parameters:
        - name: serviceId
          in: path
          description: Service ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
        400:
          description: Invalid ID
          content: {}
        404:
          description: Not found
          content: {}
      security:
        - bearer: []
  /users:
    post:
      tags:
        - user
      summary: Create a new user
      description: Create a new user
      operationId: createUser
      requestBody:
        description: The user information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        200:
          description: successful operation
          content: {}
        400:
          description: Validation error
          content: {}
  /login:
    post:
      tags:
        - auth
      summary: Authenticate user
      description: Authenticate the user. It returns the JWT token.
      operationId: login
      requestBody:
        description: The login information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        400:
          description: Validation error
          content: {}
components:
  schemas:
    Service:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        url:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
    Login:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        token:
          type: string
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
