openapi: 3.0.1
info:
  title: HealthCheck v1
  description: This app polls periodically the status of the services that belong
    to a user.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8888/api/v1
tags:
  - name: service
    description: Services management
    externalDocs:
      description: More information
      url: https://github.com/rwngallego/healthcheck/blob/master/docs/design.md
  - name: user
    description: User management
    externalDocs:
      description: More information
      url: https://github.com/rwngallego/healthcheck/blob/master/docs/design.md
  - name: auth
    description: Authentication management
    externalDocs:
      description: More information
      url: https://github.com/rwngallego/healthcheck/blob/master/docs/design.md
paths:
  /services:
    get:
      tags:
        - service
      summary: Get all the services
      description: Get a list of services and their status information
      operationId: servicesByUser
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: Number of items to skip
        - in: query
          name: limit
          schema:
            type: integer
          description: Number of items to return
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceStatus'
        400:
          description: Invalid ID
          content: {}
        404:
          description: Not found
          content: {}
      security:
        - bearer: []
    post:
      tags:
        - service
      summary: Create a new service
      description: Create a new service
      operationId: createService
      requestBody:
        description: The service information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
        required: true
      responses:
        200:
          description: successful operation
          content: {}
        400:
          description: Validation error
          content: {}
      security:
        - bearer: []
  /services/{serviceId}:
    put:
      tags:
        - service
      summary: Update service
      description: Update the service information
      operationId: updateService
      parameters:
        - name: serviceId
          in: path
          description: Service ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: The service information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
        required: true
      responses:
        200:
          description: successful operation
          content: {}
        400:
          description: Validation error
          content: {}
      security:
        - bearer: []
    delete:
      tags:
        - service
      summary: Delete service
      description: Delete the service
      operationId: deleteService
      parameters:
        - name: serviceId
          in: path
          description: Service ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: successful operation
          content: {}
        400:
          description: Invalid ID
          content: {}
        404:
          description: Not found
          content: {}
      security:
        - bearer: []
  /users:
    post:
      tags:
        - user
      summary: Create a new user
      description: Create a new user
      operationId: createUser
      requestBody:
        description: The user information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        200:
          description: successful operation
          content: {}
        400:
          description: Validation error
          content: {}
  /login:
    post:
      tags:
        - auth
      summary: Authenticate user
      description: Authenticate the user. It returns the JWT token.
      operationId: login
      requestBody:
        description: The login information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResult'
        400:
          description: Validation error
          content: {}
components:
  schemas:
    Service:
      type: object
      properties:
        name:
          type: string
          description: Name of the service
        url:
          type: string
          description: Url of the service
    ServiceStatus:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Id of the service
        name:
          type: string
          description: Name of the service
        url:
          type: string
          description: Url of the service
        status:
          type: string
          description: Current status of the service
          enum:
            - FAIL
            - OK
          example: FAIL
        created_at:
          type: string
          description: Date in which the service was created
          format: date-time
        updated_at:
          type: string
          format: date-time
          description: The last time the service information was changed
    User:
      type: object
      properties:
        username:
          type: string
          description: Username
        password:
          type: string
          format: password
          description: Password
    Login:
      type: object
      properties:
        username:
          type: string
          description: Username
        password:
          type: string
          format: password
          description: Password
    LoginResult:
      type: object
      properties:
        message:
          type: string
          description: Informative message
        token:
          type: string
          description: Authentication token
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
