version: '3.1'

services:
  healthcheck:
    build:
      context: .
    ports:
      - 8888:8888
    networks:
      - healthcheck-net
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: healthcheck
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: '1'
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS healthcheck; CREATE DATABASE IF NOT EXISTS healthcheck_test;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    networks:
      - healthcheck-net

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus:/etc/prometheus
    logging:
      driver: none
    networks:
      - healthcheck-net

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    logging:
      driver: none
    networks:
      - healthcheck-net

networks:
  healthcheck-net:
    name: healthcheck-net
