version: '3.1'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: healthcheck_test
      MYSQL_USER: healthcheck
      MYSQL_PASSWORD: healthcheck
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - healthcheck-test-net

networks:
  healthcheck-test-net:
    name: healthcheck-test-net
