global:
  scrape_interval: 10s

  external_labels:
    monitor: 'healthcheck'

scrape_configs:
  - job_name: 'healthcheck'
    scrape_interval: 10s
    static_configs:
      - targets: ['healthcheck:8888']
